spring:
  application:
    name: Community

  jwt:
    secret: ${JWT_SECRET:your-secret-key}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

imgbb:
  secret: ${IMGBB_SECRET:your-secret-key}
